# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ENV["IOS_VERSION"]="1"
    ENV["APP_VERSION"]="1.0.0"
  end

  desc "Create an app on Apple Developer and App Store Connect sites"
  lane :create_app do
    produce
  end

  desc "Upload the app to App Store Connect"
  lane :upload_ipa do
    sh("fastlane pilot upload")
  end

  desc "Grab the latest iOS version and increment it"
  lane :set_ios_version do
    version = ENV["APP_VERSION"]
    ENV["IOS_VERSION"] = latest_testflight_build_number(version: version)
  end
end
