# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ENV["IOS_VERSION"]="1"
    ENV["APP_VERSION"]="1.0.0"
  end

  desc "Create an app on Apple Developer and App Store Connect sites"
  lane :create_app do
    produce
  end

  desc "Upload the app to App Store Connect"
  lane :upload_ipa do
    notes = ENV["RELEASE_NOTES"]
    sh("fastlane pilot upload --changelog #{notes}")
  end

  desc "Grab the latest iOS version and increment it"
  lane :set_ios_version do
    version = ENV["APP_VERSION"]
    latestBuildNumber = latest_testflight_build_number(version: version)
    newBuildNumber = ((latestBuildNumber.is_a? String) ? latestBuildNumber.to_i : latestBuildNumber) + 1
    ios_version = newBuildNumber.to_s
    sh("envman add --key IOS_VERSION --value #{ios_version}")
  end
end
